{
 "title": "Dovecot Stats",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(dovecot_build_info, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Dovecot version",
   "type": "stat",
   "description": "Dovecot version",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dovecot_build_info", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Auth Stats",
   "type": "timeseries",
   "description": "Dovecot Auth Stats",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "dovecot_auth_success_total{instance=\"$instance\"} - dovecot_auth_success_total{instance=\"$instance\"} offset $__interval",
     "legendFormat": "Success Auth"
    },
    {
     "expr": "dovecot_auth_failures_total{instance=\"$instance\"} - dovecot_auth_failures_total{instance=\"$instance\"} offset $__interval",
     "legendFormat": "Failed Auth"
    }
   ]
  },
  {
   "title": "Auth Stats Duration",
   "type": "timeseries",
   "description": "Dovecot Auth Stats Duration",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "dovecot_auth_success_duration_seconds_total{instance=\"$instance\"} - dovecot_auth_success_duration_seconds_total{instance=\"$instance\"} offset $__interval",
     "legendFormat": "Auth Success Duration"
    },
    {
     "expr": "dovecot_auth_failures_duration_seconds_total{instance=\"$instance\"} - dovecot_auth_failures_duration_seconds_total{instance=\"$instance\"} offset $__interval",
     "legendFormat": "Auth Failure Duration"
    }
   ]
  },
  {
   "title": "IMAP Command Stats",
   "type": "timeseries",
   "description": "Dovecot IMAP Command Stats",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "dovecot_imap_command_total{instance=\"$instance\"} - dovecot_imap_command_total{instance=\"$instance\"} offset $__interval",
     "legendFormat": "{{cmd_name}}{{tagged_reply_state}}"
    },
    {
     "expr": "dovecot_imap_command_count{instance=\"$instance\"} - dovecot_imap_command_count{instance=\"$instance\"} offset $__interval",
     "legendFormat": "All Commands"
    }
   ]
  },
  {
   "title": "IMAP Command Stats Duration",
   "type": "timeseries",
   "description": "Dovecot IMAP Command Stats Duration",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "dovecot_imap_command_duration_seconds_total{instance=\"$instance\"} - dovecot_imap_command_duration_seconds_total{instance=\"$instance\"} offset $__interval",
     "legendFormat": "{{cmd_name}}{{tagged_reply_state}}"
    },
    {
     "expr": "dovecot_imap_command_duration_seconds_sum{instance=\"$instance\"} - dovecot_imap_command_duration_seconds_sum{instance=\"$instance\"} offset $__interval",
     "legendFormat": "All commands"
    }
   ]
  },
  {
   "title": "SMTP Commands Histogram",
   "type": "bargauge",
   "description": "Dovecot SMTP Commands Histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dovecot_smtp_command_bucket{instance=\"$instance\"}",
     "legendFormat": "{{cmn_name}}{{le}}{{status_code}}"
    }
   ]
  },
  {
   "title": "SMTP Mail Delivery Histogram",
   "type": "bargauge",
   "description": "Dovecot SMTP Mail Delivery Histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dovecot_mail_delivery_bucket{instance=\"$instance\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "SMTP Command Count",
   "type": "timeseries",
   "description": "Dovecot SMTP Command Count",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "dovecot_smtp_command_count{instance=\"$instance\"} - dovecot_smtp_command_count{instance=\"$instance\"} offset $__interval",
     "legendFormat": "{{cmd_name}}{{status_code}}"
    }
   ]
  },
  {
   "title": "SMTP Command Sum",
   "type": "timeseries",
   "description": "Dovecot SMTP Command Sum",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "dovecot_smtp_command_sum{instance=\"$instance\"} - dovecot_smtp_command_sum{instance=\"$instance\"} offset $__interval",
     "legendFormat": "{{cmd_name}}{{status_code}}"
    }
   ]
  },
  {
   "title": "Mail Delivery Count",
   "type": "timeseries",
   "description": "Dovecot Mail Delivery Count",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "dovecot_mail_delivery_count{instance=\"$instance\"} - dovecot_mail_delivery_count{instance=\"$instance\"} offset $__interval",
     "legendFormat": "Mail Delivery Count"
    }
   ]
  },
  {
   "title": "Mail Delivery Sum",
   "type": "timeseries",
   "description": "Dovecot Mail Delivery Sum",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "dovecot_mail_delivery_sum{instance=\"$instance\"} - dovecot_mail_delivery_sum{instance=\"$instance\"} offset $__interval",
     "legendFormat": "Mail Delivery Sum"
    }
   ]
  }
 ]
}